name: Build and deploy Python app to Azure Web App - 404

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show files
        run: ls -R

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "404"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BD038AFC9F124793B8CC2C2F26ED597C }}
          package: .